version: '3.9'

services:
  frontend-builder:
    container_name: frontend-builder
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "cd gamedev-web-frontend_ && npm install && npm run build"
    stdin_open: true
    tty: true

  nginx:
    container_name: nginx
    restart: always
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/gamedev-web-frontend_/dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend-builder

  postgresql:
    container_name: postgres
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  fastapi:
    container_name: fastapi-api
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    restart: always

volumes:
  pgdata:
